### ISSUE TITLE
Feature Request: Templates

### ISSUE THREAD

**Issue by merqrial** [svsool/memo#572]
Hello, 

Thank you for developing this VS Code extension. It is really a good tool to log my daily activities.
Is there a possibility to bring in template support, or is this a very big ask?

For my daily notes or retrospective meetings, I would create new notes based on a template.
For now, I can create one template folder and keep template like files and copy paste from there.

**Comment by svsool** [comment]
Hi,

I would prefer to not re-invent templates in this extension, because it can be quite time consuming and complex.

For me [auto snippet](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.auto-snippet) extension and [vscode's snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) is usually enough.

Thank you!

**Comment by Semphora** [comment]
I've found this because I was missing templating and remembered to check the issues. After a quick check I'm convinced, that snippets will do fine, for my purposes. It might be worth to add a note into the readme, so the information is easier to find.
