### ISSUE TITLE
New notes capture links to old notes with same name

### ISSUE THREAD

**Issue by memeplex** [svsool/memo#590]
With short links Memo does the right thing if a note is renamed or moved, but creating new files may wreak havoc on the knowledge base, even when all operations are done from inside vscode. As a simple example, suppose that you start with:

```
a.md
d/b.md
```

and there is a wikilink `[[b]]` inside a. Now create a new `b.md` file at the top level:

```
a.md
b.md
d/b.md
```

Now `a.md` points to `b.md` instead.

**Comment by memeplex** [comment]
A more dangerous situation. Starting from:

```
d/a.md
d/b.md
```

where `a.md` contains `[[b]]`, add `c/b.md`:

```
c/b.md
d/a.md
d/b.md
```

Now `d/a` points to `c/b`. If `d` was giving some context for the notes inside, for example if `d` were a project, now context (project) `c` captures links from `d`.

**Comment by svsool** [comment]
It's expected behavior with the current implementation. I documented how short links work [here](https://github.com/svsool/memo/blob/master/help/Features/Creating%20notes%20from%20links.md#short-links). Short link location can change if tree changes and non-unique filenames added. For predictability, links are sorted naturally with the shallowest (often shortest) path first, and then the first entry picked. If there are many cases with non-unique filenames in your knowledge base then short links format is probably not the best tool and  long links format should be used instead.
